# Generated by Django 5.1 on 2024-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_rename_user_chatbot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('trained', 'Trained'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('training', 'Training')], default='initialized', max_length=20),
        ),
    ]
