# Generated by Django 5.1 on 2024-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_chatbot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='training_step',
            field=models.CharField(blank=True, choices=[('scraping', 'Scraping Website'), ('processing', 'Processing Content'), ('extraction', 'Extracting Questions and Responses'), ('augmentation', 'Augmenting Data'), ('validation', 'Validating Training File'), ('training', 'Training Model'), ('completed', 'Completed')], max_length=50, null=True),
        ),
    ]
