# Generated by Django 5.1 on 2024-08-21 20:24

import backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image_alter_customuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.users.models.profile_image_directory_path),
        ),
    ]
